export const COLORS = {
  primaryBackground: '#fff',
  primaryText: '#000000',
  secondaryBackground: '#EFEFEF',

  //   subText: '#B1B1B1',
  //   error: 'red',
  //   blue: '#376AED',
  //   primaryBlack: '#000',
  //   primaryYellow: '#F8A528',
  //   primaryGreen: '#158A43',
  //   primaryText: '#fff',
  //   primaryGray: '#E0E0E0',
  //   textGray: '#9E9E9E',
  //   textBlack: '#2C2C2C',
  //   textGray1: '#B8C2CC',
  //   gray: '#BDBDBD',
  //   white: 'white',
  //   danger: '#ff4444',
  //   secondaryBackground: '#d9dbda',
};
